name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Set up Android SDK
        run: |
          sudo apt-get install -y openjdk-8-jdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip
          yes | ./cmdline-tools/bin/sdkmanager --sdk_root=${{ github.workspace }}/android-sdk --licenses
          ./cmdline-tools/bin/sdkmanager --sdk_root=${{ github.workspace }}/android-sdk "platforms;android-29" "build-tools;29.0.2"

      - name: Build APK
        run: |
          buildozer android debug
